//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvvmTest.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MvvmTest.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        internal static string guestUser {
            get {
                return ResourceManager.GetString("guestUser", resourceCulture);
            }
        }
        
        internal static string mobileNumberCaps {
            get {
                return ResourceManager.GetString("mobileNumberCaps", resourceCulture);
            }
        }
        
        internal static string passwordCaps {
            get {
                return ResourceManager.GetString("passwordCaps", resourceCulture);
            }
        }
        
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        internal static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        internal static string mobileNumber {
            get {
                return ResourceManager.GetString("mobileNumber", resourceCulture);
            }
        }
        
        internal static string countryCode {
            get {
                return ResourceManager.GetString("countryCode", resourceCulture);
            }
        }
        
        internal static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        internal static string validationError {
            get {
                return ResourceManager.GetString("validationError", resourceCulture);
            }
        }
        
        internal static string invalidMobileNoError {
            get {
                return ResourceManager.GetString("invalidMobileNoError", resourceCulture);
            }
        }
        
        internal static string circular {
            get {
                return ResourceManager.GetString("circular", resourceCulture);
            }
        }
        
        internal static string officeBeareres {
            get {
                return ResourceManager.GetString("officeBeareres", resourceCulture);
            }
        }
        
        internal static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        internal static string groupIntro {
            get {
                return ResourceManager.GetString("groupIntro", resourceCulture);
            }
        }
        
        internal static string monthlyGathering {
            get {
                return ResourceManager.GetString("monthlyGathering", resourceCulture);
            }
        }
    }
}
